services:
  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
      target: dev
    container_name: aftermath-backend
    command: sh -c "npm ci && npm run migrate && npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app:Z
      - /app/node_modules
    env_file:
      - ./backend/.env
    environment:
      PORT: "3000"
    networks:
      - aftermath-net

networks:
  aftermath-net:
    driver: bridge
